version: "3.3"
services:
  addition:
    build:
      context: ./addition/
      dockerfile: Dockerfile
    links:
      - jaeger
    ports:
      - "8081:80"
  multiplication:
    build:
      context: ./multiplication/
      dockerfile: Dockerfile
    environment: 
      ADDITION_URL: "http://addition/"
    links:
      - jaeger
      - addition
    ports:
      - "8082:80"
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.18
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - "9411:9411"
      - "5775:5775/udp"
      - "5778:5778"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "14250:14250"
      - "14268:14268"
      - "16686:16686"
